# Generated by Django 3.2.15 on 2025-04-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sinistre', '0019_auto_20250402_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackEtape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('libelle', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Etape',
                'verbose_name_plural': 'Etape',
                'db_table': 'track_etape',
            },
        ),
        migrations.CreateModel(
            name='TrackFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_systeme', models.CharField(blank=True, max_length=255, null=True)),
                ('montant_facture', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('nombre_feuilles_soins', models.DecimalField(decimal_places=6, max_digits=20, null=True)),
                ('date_reception', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'track_facture',
                'verbose_name_plural': 'track_facture',
                'db_table': 'track_facture',
            },
        ),
        migrations.CreateModel(
            name='TrackEtapeFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observation', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('etape', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='sinistre.tracketape')),
                ('track_facture', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='sinistre.trackfacture')),
            ],
            options={
                'verbose_name': 'Etape Facture',
                'verbose_name_plural': 'Etapes Factures',
                'db_table': 'track_etape_facture',
            },
        ),
    ]
