# Generated by Django 3.2.15 on 2025-04-03 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sinistre', '0020_tracketape_tracketapefacture_trackfacture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracketapefacture',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='tracketapefacture',
            name='etape',
        ),
        migrations.RemoveField(
            model_name='tracketapefacture',
            name='track_facture',
        ),
        migrations.RemoveField(
            model_name='trackfacture',
            name='created_by',
        ),
        migrations.DeleteModel(
            name='TrackEtape',
        ),
        migrations.DeleteModel(
            name='TrackEtapeFacture',
        ),
        migrations.DeleteModel(
            name='TrackFacture',
        ),
    ]
