# Generated by Django 3.2.15 on 2025-04-02 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagneprospect',
            name='campagne',
        ),
        migrations.RemoveField(
            model_name='campagneprospect',
            name='prospect',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='adherent_principal',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='aliment',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='aliment_adherent_principal',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='bureau',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='civilite',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='formulegarantie',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='pays_activite_professionnelle',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='pays_naissance',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='pays_residence',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='police',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='prospect',
            name='qualite_beneficiaire',
        ),
        migrations.DeleteModel(
            name='CampagneAppmobileProspect',
        ),
        migrations.DeleteModel(
            name='CampagneProspect',
        ),
        migrations.DeleteModel(
            name='Prospect',
        ),
    ]
