# Generated by Django 3.2.15 on 2025-04-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('grh', '0002_auto_20250402_0127'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campagneappmobile',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campagneappmobile',
            name='formulegarantie',
        ),
        migrations.RemoveField(
            model_name='campagneappmobile',
            name='police',
        ),
        migrations.DeleteModel(
            name='Campagne',
        ),
        migrations.DeleteModel(
            name='CampagneAppmobile',
        ),
    ]
