# Generated by Django 3.2.15 on 2025-04-02 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0027_cartedigitaldematerialisee_policeclient_vehiculepolice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grh', '0003_auto_20250402_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampagneAppmobile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Campagne_appmobile',
                'verbose_name_plural': 'campagne_appmobile',
                'db_table': 'campagne_appmobile',
            },
        ),
        migrations.CreateModel(
            name='Campagne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=255, null=True)),
                ('code', models.CharField(max_length=25, null=True, unique=True)),
                ('lien', models.CharField(max_length=255, null=True)),
                ('date_debut', models.DateTimeField()),
                ('date_fin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('statut', models.CharField(choices=[('VALIDE', 'Valide'), ('SUPPRIME', 'Supprime'), ('BROUILLON', 'Brouillon'), ('CLOTURE', 'Cloture')], default='VALIDE', max_length=15, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('formulegarantie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.formulegarantie')),
                ('police', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='production.police')),
            ],
            options={
                'verbose_name': 'Campagne',
                'verbose_name_plural': 'campagnes',
                'db_table': 'campagne',
            },
        ),
    ]
