# Generated by Django 3.2.15 on 2025-04-02 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='InfoActe',
        ),
    ]
